apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-metrics-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-metrics-app
  template:
    metadata:
      labels:
        app: nodejs-metrics-app
    spec:
      containers:
      - name: nodejs-metrics-app
        image: mohamedomarfarook/nodejs-metrics-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-metrics-app-service
  namespace: default
spec:
  selector:
    app: nodejs-metrics-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
