apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nodejs-metrics-app-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: nodejs-metrics-app
  endpoints:
    - port: "80"
      path: /metrics
      interval: 15s
